### ISSUE TITLE
Avoid mutating function arguments

### ISSUE THREAD

**Issue by pwolaq** [andrerpena/react-mde#10]
There are few places where function arguments are mutated. It's a good practice to avoid such behaviour by creating new variables instead of mutating existing ones.

Example:
```javascript
export function makeHeader(text, selection, insertionBefore) {
    selection = selectCurrentWorkIfCarretIsInsideOne(text, selection); // mutating selection variable
```

**Comment by andrerpena** [comment]
I'm not in favor of this either. I'll fix it.

**Comment by andrerpena** [comment]
This has been addressed in the new 1.* version
