### ISSUE TITLE
Editor broken on Android (using Chrome)

### ISSUE THREAD

**Issue by samschl** [andrerpena/react-mde#111]
Hi there

I am experiencing issues using the editor on Chrome (v. 67.0.33.96.81) on Android (v. 8.0.0). 
When I start typing every word is removed after adding a space. I tested this locally in my own project as well as on the demo on GitHub. 

Cheers

**Comment by andrerpena** [comment]
@samschl Thanks for reporting. I'll take a look

**Comment by rej156** [comment]
+1 on this for Kauri.io!

**Comment by andrerpena** [comment]
I'm sorry for this. I'll prioritize this issue this weekend!

**Comment by andrerpena** [comment]
I still did not solve the problem, but 2 hours into it (just for being able to remote debug my Android device), I'm able to see the problem in the desktop DevTools. No exception is thrown in JavaScript. I'll continue to dig into it.

![image](https://user-images.githubusercontent.com/1581429/41507972-3d569ad8-723d-11e8-8277-4acb7083e68b.png)

**Comment by andrerpena** [comment]
After quite a while trying to debug it on Chrome for Android I came to the conclusion it must be a Draftjs problem. I made a quick research and there it is: https://github.com/facebook/draft-js/issues/102. This is so sad. It took me so much to migrate React-mde to Draft without knowing it has issues with Chrome for Android =/

**Comment by samschl** [comment]
Hi andrerpena, thank you very much for looking into this issue, I really appreciate it. I had a quick look into the linked issue and it is a pity that draft is not mentioning that it has issues on Chrome for Android.

**Comment by AndrewMorsillo** [comment]
Darn, I was thinking of using this lib as it sounds perfect for my project but I have a lot of users on mobile Chrome... Kinda crazy that draftjs.org advertises cross browser abstraction yet it is broken on android chrome for over 2 years with no movement from the developers ☹️
