### ISSUE TITLE
Unable to handle overflow for the preview and editor textarea

### ISSUE THREAD

**Issue by sunpreetsingh19** [andrerpena/react-mde#115]
Hello, I am facing an issue regarding handling the height and overflow of editor textarea as well as preview. I don't know if I am missing something, I tried adding an overflow to the parent container but the problem is,
 it also scrolls up the toolbar. 

![screenshot from 2018-06-16 12-25-40](https://user-images.githubusercontent.com/22357469/41500568-1f722360-7162-11e8-85e9-0d8609070740.png)

**Comment by aliogaili** [comment]
+ any input on this issue? sounds like a basic requirement.

**Comment by andrerpena** [comment]
This problem should be fixed on version 6.0.0-alpha.1. I'm sorry but this contains a number of [breaking changes](https://github.com/andrerpena/react-mde/blob/master/docs-md/ChangeLogMigrating.md#from-5-to-6). Please let me know if it does not work for you.
