### ISSUE TITLE
Hashtag without following space shouldn't be interpreted as header.

### ISSUE THREAD

**Issue by mawek** [andrerpena/react-mde#12]
It is common to have twitter like tags in text and they shouldn't be interpreted as headers as mentioned [here](https://talk.commonmark.org/t/heading-not-working/819/4)

**Comment by andrerpena** [comment]
@mawek , thanks for reporting. But this is actually a problem with https://github.com/showdownjs/showdown. The most I can do is to allow for alternative MD parsers. 

Another thing I want to do is to allow (optionally) remote rendering of the Preview, like GitHub, in such a way that the markdown you'd be seeing in the preview would be exactly the one generated by your server-side engine.

**Comment by andrerpena** [comment]
I'm closing this down because there isn't much I can do now. Feel free to reopen if you have an ideia :)
