### ISSUE TITLE
How to change default toolbar (appearance)?

### ISSUE THREAD

**Issue by yehudamakarov** [andrerpena/react-mde#124]
This type of project is new to me. Just trying to edit the toolbar if possible. I tried to look at the source in my node_modules folder but it seems to be precompiled with a .js folder. I also tried to go through the component hierarchy in developer tools. (Note - I get an `Unknown` component for the toolbar.) I can't figure out how and where I'd do this. 
When I studied the "React-mde is designed to be composable and to facilitate new layouts:" picture, I wasn't able to find exactly where and how I can go about editing these components or props.

I want to be able to remove a button, or edit it. Size and icon; and call backs that get triggered on their press.

It seems I need to figure out how to add a command like in the story book example, but also keep a specified selection of buttons on the tool bar.

Any help appreciated.

**Comment by yehudamakarov** [comment]
I tried something like this which successfully resizes the icons. 

```
<ReactMde
                    buttonContentOptions={{
                        iconProvider: name => <i className={`fas fa-${name} fa-2x`} aria-hidden="true"/>,
                    }}
                    layout='horizontal'
                    onChange={this.handleValueChange}
                    editorState={this.state.mdeState}
                    generateMarkdownPreview={(markdown) => Promise.resolve(this.converter.makeHtml(markdown))}
                />
```

**Comment by Eugleo** [comment]
@yehudamakarov I'd like to be able to hide some of the icons. Is that currently possible?
