### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by projecteon** [andrerpena/react-mde#127]
Hi,

Are there any thoughts or plans to add localization in any way?

https://github.com/ryandrewjohnson/react-localize-redux
https://github.com/stefalda/react-localization

**Comment by andrerpena** [comment]
Hey @projecteon , can you please clarify what type of string is not localizable?

**Comment by projecteon** [comment]
![image](https://user-images.githubusercontent.com/2820276/43893824-93fce024-9bd0-11e8-96e8-a49191fb44c5.png)


The aria labels for commands (I'm using css to make them hover pop for information to the user) as well as the Code/Preview tabs in tab mode.

**Comment by andrerpena** [comment]
This problem should be fixed on version 6.0.0-alpha.1. I'm sorry but this contains a number of [breaking changes](https://github.com/andrerpena/react-mde/blob/master/docs-md/ChangeLogMigrating.md#from-5-to-6). Please let me know if it does not work for you.
