### ISSUE TITLE
Possible to pass a ref to the inner textarea/editing area?

### ISSUE THREAD

**Issue by mikeappell** [andrerpena/react-mde#129]
Hey there 😃

I'm conditionally rendering the Mde, and would like it to gain focus upon rendering. However, I'm struggling to pass a ref to the inner editing area which would allow me to call `ref.focus()`.

I don't think that `textAreaProps` is supported anymore – what's the best way to accomplish what I'm aiming for?

Thanks in advance.

**Comment by dnlfrst** [comment]
# Problem
You want to have `textarea` of the editor focused upon rendering, i. e. automatically focus `textarea`.

# Solution
There's no need to use a `ref`. Instead, you can use `textAreaProps` as you already mentioned. I'm not sure about which version you were talking, but at least in version 7.0.3 `textAreaProps` works like a charm.

## Code
Using the following gives you an automatic focus when rendering the editor:
```javascript
<ReactMde textAreaProps={{ autoFocus: true }} />
```
You can even do this conditionally using hooks or `state`. See [here](https://codesandbox.io/s/yqqrpn9869) for a full example.

**Comment by andrewhead** [comment]
Thanks to everyone maintaining this awesome library. I needed to get a ref to the textarea so that I could automatically resize it when the text changed. I got a ref to the textarea like this:

```jsx
const ref = useRef<ReactMde>(null);

<ReactMde
    ref={ref}
    ... />

if (ref.current !== null) {
    const textarea = ref.current.textAreaRef;
}

```

I know the `ReactMde.textAreaRef` property isn't in the document API in the README, but it worked for me in a pinch and I don't necessarily need to keep in sync with future changes to react-mde, so perhaps this could work for you too if you're in a similar situation.

**Comment by nikolalsvk** [comment]
Is it possible to do so in the latest version? I am trying to implement the auto-resize feature. The idea is to have the textarea expand and contract when a user types text.

**Comment by nikolalsvk** [comment]
I managed to do it in 11.0.6 version like so:

```tsx
const MarkdownEditor = props => {
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  // resize textarea to content size on render
  useEffect(() => {
    if (textareaRef !== null && textareaRef.current !== null) {
      resize(textareaRef.current)
    }
  }, [])

  // resize helper method
  const resize = (htmlElement: HTMLTextAreaElement) => {
    htmlElement.style.height = 'inherit'
    htmlElement.style.height = `${htmlElement.scrollHeight}px`
  }

  return (
    <ReactMde
      ... // other props
      childProps={{
        textArea: {
          onKeyUp: (event: React.KeyboardEvent<HTMLTextAreaElement>) => {
            const target = event.target as HTMLTextAreaElement

            resize(target)
          }
        }
      }}
      refs={{
        textarea: textareaRef
      }}
      ... // other props
    />

  )
}
```

It would be nice if we can update the docs with some of the examples. There is some information about `childProps` prop, but nothing about `refs`. I had to dig into the source code to find it.

I will try to take a stab at updating the docs, it is a very helpful library and good docs would make it even better.
