### ISSUE TITLE
Hitting a command twice should undo commands

### ISSUE THREAD

**Issue by andrerpena** [andrerpena/react-mde#13]

**Comment by colshacol** [comment]
I agree, I think it should. I will look into this and see if I can provide a PR for the feature.

**Comment by ForumT** [comment]
Any progress on this1?

**Comment by andrerpena** [comment]
I am currently working on this PR for image upload https://github.com/andrerpena/react-mde/pull/243 and it will probably take a couple of days more.. Maybe I can take this afterwards
