### ISSUE TITLE
how could i compile the src into umd file?

### ISSUE THREAD

**Issue by lchrennew** [andrerpena/react-mde#131]
how could i compile the src into umd file?

**Comment by andrerpena** [comment]
Currently, the released NPM module contains ES5 transpiled JavaScript code and SCSS/CSS, but it is up to you to generate UMD modules if you need it. 

Do you have a suggestion about how to make it better? Can you point to a React library that does what you need that React-mde does not?

**Comment by andrerpena** [comment]
I'll investigate using Rollup to release a UMD bundle
