### ISSUE TITLE
Stripped newlines still show up in Editor window

### ISSUE THREAD

**Issue by mikeappell** [andrerpena/react-mde#134]
In the function I have for `onChange` I use the following logic:
```
handleMarkdownChange = (markdownState) => {
    const newMarkdownState = { ...markdownState, markdown: markdownState.markdown.trim() };
    this.setState({ markdownState: newMarkdownState });
}
```

The reason for the `trim()` is that I trigger some custom logic on enter (specifically, hiding the markdown editor), and so I want to prevent them from being saved. And it _does_ successfully update state without the newline characters.

However, the editor window still shows the newlines despite state lacking them, and I'm not sure how to prevent this. For instance, if we add `console.log(newMarkdownState.markdown)` at the end of the above function we see the following behavior:

![aug-22-2018 12-50-23](https://user-images.githubusercontent.com/15162965/44477961-3393ad00-a60a-11e8-9ad2-d7a2c5da4ea8.gif)

State lacks the newlines, but the Editor pane still has them, and so when you hit enter a few times and begin typing again the newlines are preserved between the two.

Here's the full list of props I'm passing to the MdeEditor: (I'm creating a custom Command button off-screen.)
```
const customLayoutOptions = {
  editorClassName: 'custom-markdown-editor',
  previewClassName: 'custom-markdown-preview',
};

<ReactMarkdownEditor
  key={this.props.text}
  layout="vertical"
  onChange={this.handleMarkdownChange}
  editorState={this.state.markdownState}
  generateMarkdownPreview={markdown => Promise.resolve(this.converter.makeHtml(markdown))}
  buttonContentOptions={{ iconProvider: name => <i className={`fa fa-${name}`} /> }}
  commands={ReactMdeCommands.getDefaultCommands().concat([[CustomMarkdownEditor]])}
  layoutOptions={customLayoutOptions}
/>
```

Any input on how to prevent the Editor from preserving these newlines would be appreciated.

**Comment by andrerpena** [comment]
I'm sorry I've been away for a while. I'll look into it ASAP

**Comment by andrerpena** [comment]
I'm not using Draft state anymore so I assume this problem is no longer relevant
