### ISSUE TITLE
Use font-awesome in a more "react" way

### ISSUE THREAD

**Issue by cjs840312** [andrerpena/react-mde#139]
I like this project very much, however,
since this markdown editor is target for react use,
it seems that the use of font-awesome should be more "react" style.
Adding `<script>` in html may conflict with other package and is not that elegant.

The following link in the official website for using font-awesome in react. 
https://fontawesome.com/how-to-use/on-the-web/using-with/react

Hope it can improve in the next version!

**Comment by andrerpena** [comment]
React-mde supports custom icon providers, meaning you can provide a customized way to convert an "icon name" into a React element: https://github.com/andrerpena/react-mde#customizing-icons

If this doesn't solve your problem, please let me know.
