### ISSUE TITLE
Buttons type

### ISSUE THREAD

**Issue by SergeyShablenko** [andrerpena/react-mde#140]
Make buttons type configurable or make them with type "button" to prevent form submitting

**Comment by cjs840312** [comment]
I think this is the same problem as #138

**Comment by andrerpena** [comment]
This problem should be fixed on version 6.0.0-alpha.1. I'm sorry but this contains a number of [breaking changes](https://github.com/andrerpena/react-mde/blob/master/docs-md/ChangeLogMigrating.md#from-5-to-6). Please let me know if it does not work for you.
