### ISSUE TITLE
Prop for default tab

### ISSUE THREAD

**Issue by lukezavrel** [andrerpena/react-mde#141]
Hi, 
would it be possible (or is there a way) to set the initial tab to `preview` on the `tabbed` layout?
Thanks for your answer.

**Comment by andrerpena** [comment]
So, the best way to do that, I think, is to make react-mde completely controlled and expect you to pass the current tab to it. This will make it a bit less straight-forward but I think it is the best way to go. I'll make the change.

**Comment by andrerpena** [comment]
I'm doing it now
