### ISSUE TITLE
Async command is no available in v6.0.0-alpha.1

### ISSUE THREAD

**Issue by Dearkano** [andrerpena/react-mde#145]
It seems that there's no longer support for async command anymore.

I change 'handleCommand' in ReactMde.tsx and it works.
```
  handleCommand = (command: Command) => {
    if (!command.execute) return;
    const newEditorState = command.execute(this.cachedDraftState);
    if(newEditorState.constructor.name==="Promise"){
      (newEditorState as any).then((result) =>  this.handleTextChange(result));
    }else{
      this.handleTextChange(newEditorState);
    }
  };
```

**Comment by andrerpena** [comment]
@Dearkano , supporting async commands would make the code more complicated because we would have to figure out a way to lock the editor while the Promise does not return. Also, I could't find a compelling reason to have to support it.
