### ISSUE TITLE
Bullet point and numbered lists don’t continue when you press the return key to move to the next line

### ISSUE THREAD

**Issue by leehillz** [andrerpena/react-mde#146]
- Add a bullet point or numbered list
- Enter some text and hit the return key
- The list isn't continued

**Comment by andrerpena** [comment]
I'm sorry. Neither Stackoverflow or Github has this feature and my goal is to have feature parity with Github.

**Comment by MikkCZ** [comment]
Hi @andrerpena .

Currently GitHub does support this - pressing enter continues the list, creating a new item. Would you consider changing the behavior?
