### ISSUE TITLE
l18n props is not used by MdeToolbar

### ISSUE THREAD

**Issue by Betree** [andrerpena/react-mde#147]
In `6.0.0-alpha.1`, passing `l18n` has no effect. MdeToolbar always use the default `enL18n.write` instead of `props.l18n`. 

https://github.com/andrerpena/react-mde/blob/f03775468287db91909d461ded7b322c18c9e23c/src/components/MdeToolbar.tsx#L36-L49

**Comment by SergeyShablenko** [comment]
When will this change be applied?

**Comment by SergeyShablenko** [comment]
why not just replace `enL18n` with `this.props.l18n` ? It would be much faster for you to just push it than for me to create pull request e.t.c

**Comment by Betree** [comment]
@SergeyShablenko I'm not a maintainer here, just a contributor like you :slightly_smiling_face: It would take me the same time

**Comment by andrerpena** [comment]
I'm fixing this now.. sorry
