### ISSUE TITLE
Demo toolbar doesn't work with Firefox

### ISSUE THREAD

**Issue by kasbah** [andrerpena/react-mde#15]
Neat project! The demo is a bit broken on Firefox unfortunately. The buttons on the toolbar simply do nothing whatsoever. The rest of the functionality seems to work fine. 

Tested with Firefox 50.1.0 on Ubuntu without any extensions. No errors are reported on the console.

**Comment by andrerpena** [comment]
Thanks for reporting. I'll check it out.

**Comment by andrerpena** [comment]
Confirmed

**Comment by jakub-gawlas** [comment]
Bug is caused by `src/ReactMde.js -> executeCommand -> line 61`
```js
document.execCommand("insertText", false, newValue.text);
```
`insertText` doesn't work proper with textarea on Firefox

maybe someone have a solution?

**Comment by andrerpena** [comment]
@jakub-gawlas Thank you very much for pinpointing the problem. I don't have a solution right now but I'll try to figure out one.

**Comment by andrerpena** [comment]
I'm having a really hard time with this bug.

If I replace

    document.execCommand("insertText", false, newValue.text);

with 

    textarea.value = newValue.text

It works perfectly on Firefox but now Chrome doesn't preserve the history of the element so Ctrl + Z doesn't work.

I'm rethinking controlling the component state myself, but the last time I tried I ran into other problems :(

**Comment by andrerpena** [comment]
I'm going to implement my own history-manager for the `textarea`. It's the only way I'm seeing this to work

**Comment by andrerpena** [comment]
Now that I've restarted maintaining this component, I've realized that it still doesn't work on the latest version of Firefox and this is my top 1 priority now.

**Comment by andrerpena** [comment]
Really. I couldn't make it to work together with history so I decided to switch problems in favor of a better architecture and a possibly easier problem to solve.

Now the execution of a command will just trigger `onChange` passing whatever the command returned (containing the value and the selection). This is the cleanest/simplest thing to do. It also works on Firefox.

The downside is that now history is messed up after a command is executed and undo with Ctrl + Z is not working. I think I'll have to write my own history control.
