### ISSUE TITLE
Add release tags

### ISSUE THREAD

**Issue by jleclanche** [andrerpena/react-mde#157]
Any chance npm release tags can be pushed to git as well? Right now only 5.5.x prereleases show up:

https://github.com/andrerpena/react-mde/releases

**Comment by andrerpena** [comment]
Good point. I'll generate a tag now

**Comment by andrerpena** [comment]
Just did for 7.0.3. I will do it for future releases as well. Just curious.. Why is it important for you? Thanks

**Comment by jleclanche** [comment]
Thanks! Having the tags on git is just super useful to track releases and know the health of the project based on git, rather than having to go on npm :)

**Comment by andrerpena** [comment]
Makes sense. I'll keep it updated. Thanks
