### ISSUE TITLE
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in

### ISSUE THREAD

**Issue by ramast** [andrerpena/react-mde#159]
```
"react": "^15.5.4"
"react-mde": "^7.0.3",
```

```
import ReactMde from "react-mde"


// ---> In render() 
                        <ReactMde className="col-11" value={user_review.text}
                            generateMarkdownPreview={false} selectedTab="write" minEditorHeight={100}
                            maxEditorHeight={400}
                            textAreaProps={{
                                name: "body", maxLength: 1500, rows: 12,
                                required: true}}
                            onChange={this.onReviewBodyChange.bind(this)}/>
```

Error:

```Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `ReactMde`.
    in ReactMde```

**Comment by andrerpena** [comment]
Checking

**Comment by andrerpena** [comment]
I just updated the demos and I cannot reproduce. Please provide more details. I'll be happy to reopen


- [Demo](http://andrerpena.me/react-mde/). 
- [Demo on CodeSandbox](https://codesandbox.io/s/vm1k17ymq0) (please try to reproduce forking this one here)
- [Demo *source* in TypeScript](https://github.com/andrerpena/react-mde/tree/master/demo).
- [Demo *source* in JSX](https://github.com/andrerpena/react-mde-test).

**Comment by ramast** [comment]
I was able to reproduce this bug on CodeSandbox simply by changing react version in package.json

```
-    "react": "16.8.3",
-    "react-dom": "16.8.3",
+    "react": "15.5.4",
+   "react-dom": "15.5.4",
```
