### ISSUE TITLE
Publish a new version to update npm package

### ISSUE THREAD

**Issue by wbobeirne** [andrerpena/react-mde#160]
Thanks for removing npm with [this release](https://github.com/andrerpena/react-mde/releases/tag/7.0.3), however it looks like there was a 7.0.3 that happened 22 days ago, so npm doesn't have this removal of npm. Could you bump and push a new release so that npm doesn't have this package anymore as well?

**Comment by andrerpena** [comment]
Oh my god I forgot to publish. My bad. Thanks. I will fix

**Comment by andrerpena** [comment]
It is done. I'm really sorry for the late
