### ISSUE TITLE
Highlight image url portion when clicking image button

### ISSUE THREAD

**Issue by jleclanche** [andrerpena/react-mde#163]
Clicking the image button currently looks like this:

![image](https://user-images.githubusercontent.com/235410/54301763-de2be700-45bf-11e9-9d22-41883231f50b.png)

I suggest changing it to behave this way:

![image](https://user-images.githubusercontent.com/235410/54301791-eedc5d00-45bf-11e9-828e-a79566824eb2.png)

When inserting an image it's most likely that the user will insert the image's url immediately, rather than the (optional) alt text.

Might be beneficial to change `image-url` to something like `https://example.com/your-image.png` instead, as well.

**Comment by andrerpena** [comment]
Right. I will do it now

**Comment by qingsong81** [comment]
Module not found: Error: Can't resolve './strikeThroughCommand' in ‘xxxx/proj/node_modules/react-mde/lib/js/commands'
