### ISSUE TITLE
Version 7.0 doesn't contain dist folder

### ISSUE THREAD

**Issue by pawlowskim** [andrerpena/react-mde#164]
Latest versions doesn't have dist folder so it cannot be used. It works with 6.0.

Moreover, I think that `ReactMde` have wrong import for class names. It should be 
`const classNames = require("classnames");` 
or
`import * as classNames from "classnames"`

**Comment by andrerpena** [comment]
Yes, v7 does not contain a `dist` folder but why do you need it? It does work. There is a CodeSandbox demo here: https://codesandbox.io/s/vm1k17ymq0 and also a full demo here: https://github.com/andrerpena/react-mde-test

Can you please elaborate?

**Comment by andrerpena** [comment]
Closing as no more details were given
