### ISSUE TITLE
Using commands in preview throws "Uncaught TypeError: Cannot read property 'selectionStart' of null"

### ISSUE THREAD

**Issue by dnlfrst** [andrerpena/react-mde#168]
# Problem
Using any of the commands in the header while inside the preview tab throws an error:
```
Uncaught TypeError: Cannot read property 'selectionStart' of null
```

# Steps to Reproduce

1. Open the [demo](http://andrerpena.me/react-mde/).
2. Click the `Preview` tab.
3. Click onto any button in the header or select a heading.
4. Observe the above error being thrown in the console.

# Possible Solution
Editing is not going to happen while inside the preview tab, consequently, there should be no actions visible to the user that suggest otherwise. If the action buttons remain visible, the should at least be in a disabled state.

**Comment by andrerpena** [comment]
Fixed by https://github.com/andrerpena/react-mde/commit/5054649d2b28ab29ef10f89b85309d70d37f7cd4

**Comment by andrerpena** [comment]
Because the behavior for Github is to hide the button bar, I'm doing exactly the same.
Thanks for reporting
