### ISSUE TITLE
the commands/strikethroughCommand.tsx is named wrong

### ISSUE THREAD

**Issue by susas3** [andrerpena/react-mde#174]
The same problem has been resolved in 7.3.2 in https://github.com/andrerpena/react-mde/issues/171, but there is again in the latest version (7.3.4).

**Comment by dcrtantuco** [comment]
same error happens on 7.3.2

**Comment by andrerpena** [comment]
Thanks to @dcrtantuco fixed on https://github.com/andrerpena/react-mde/pull/175
