### ISSUE TITLE
Prop to disable tab selection of toolbar buttons

### ISSUE THREAD

**Issue by tibetsprague** [andrerpena/react-mde#178]
In my form i want to be able to tab from another field directly into the react-mde editor, but it is instead selecting and tabbing through the buttons in the toolbar (without any indication they are selected.) It would be ideal to have a prop that sets tabindex="-1" for all the buttons in the toolbar.

**Comment by tibetsprague** [comment]
I'll add that I figured out how to mostly get this to work by adding { "tabIndex": -1 } to the buttonProps for all the commands in my toolbar, but that doesnt work for the Write/Preview tab buttons

**Comment by andrerpena** [comment]
Ok. Makes sense. I will do it

**Comment by andrerpena** [comment]
This does not solve your problem completely but it helps:

https://github.com/andrerpena/react-mde/releases/tag/7.5.0

**Comment by andrerpena** [comment]
![image](https://user-images.githubusercontent.com/1581429/60212391-71ccaf00-9861-11e9-9b21-f2e33eb05576.png)

**Comment by andrerpena** [comment]
As a next step, I'm making it possible to set default props to all buttons including the tabs, so it will be possible to set the tabindex to -1 on the tabs as well

**Comment by tibetsprague** [comment]
@andrerpena thank you!

**Comment by tibetsprague** [comment]
any update on this @andrerpena ?

**Comment by andrerpena** [comment]
@tibetsprague Sorry. Releasing a version with this feature in 30 minutes.. Hold on!

**Comment by andrerpena** [comment]
![image](https://user-images.githubusercontent.com/1581429/75822484-54f95b80-5da0-11ea-8c68-ab9a4caafc44.png)
