### ISSUE TITLE
Impossible to create custom commands with Typescript

### ISSUE THREAD

**Issue by projecteon** [andrerpena/react-mde#181]
Its impossible to create new/custom commands due to missing exports.

See the videCommand.ts in [CodeSandbox](https://codesandbox.io/s/vigorous-grass-bw5km)

**Comment by humont** [comment]
you don't need to run `commands
          .getDefaultCommands()
          .concat([{ commands: [videoCommand] }])}`

as the component automatically adds all the default ones. Just add your custom comands.

```jsx
<ReactMde
  ...
  toolbarCommands={[...all the defaults, ["custom-command-one"]]}
  commands={{
    'custom-command-one': customCommandOneHandler,
  }}
/>
```
