### ISSUE TITLE
Readonly mode displaying only html

### ISSUE THREAD

**Issue by projecteon** [andrerpena/react-mde#183]
In version 5 there was an export of the ReactMdePreview controller. This is no longer exported. Could something similar be added in for displaying readonly modes without toolbars or tabs?

**Comment by andrerpena** [comment]
I would be willing to add this feature if React-mde was responsible for generating the preview, but it is not. It is your responsibility to either use Showdown or a similar library to generate HTML out of the Markdown, or use [React Markdown](https://github.com/rexxars/react-markdown) as a preview component. The only reason I can see for you to use React-mde as a preview is to re-use the CSS. But then, just import the CSS

![image](https://user-images.githubusercontent.com/1581429/60756475-d9bb8c00-9ffd-11e9-85e6-affd0f19f691.png)

Do you have a use case I did not think about? Or a compelling reason?

**Comment by projecteon** [comment]
Not other than having to know and specify the correct classnames for the preview (with wrapper). If those changes its an unknown breaking change on package update.

**Comment by andrerpena** [comment]
@projecteon . Fair enough. I will investigate if I can easily export the markdown viewer component so you can use it independently. I think it is the most elegant solution

**Comment by projecteon** [comment]
That was what I had in mind :) 
Thanks!

**Comment by andrerpena** [comment]
I'm now exporting all components. Please feel free to open it again in case that does not solve your problem. By the way, sorry but only now I resumed working on React-mde

Commit: https://github.com/andrerpena/react-mde/commit/59a6939391753b88516d11a5dc0f98c52e325818
