### ISSUE TITLE
Needs option to NOT put Preview in dark theme

### ISSUE THREAD

**Issue by MagnusBrzenk** [andrerpena/react-mde#193]
I don't know why preview is dark theme by default. It means that I can't see the text in code blocks because both the background and text are near to white.

I would make light theme the default and, at best, create an option for dark theme (as well as to solve the clash of colors)

**Comment by andrerpena** [comment]
@MagnusBrzenk I will check now.

**Comment by andrerpena** [comment]
@MagnusBrzenk, can you please let me know which OS and browser are you using? Just tested on Chrome on Mac, and there is no inconsistency in the color scheme:

![image](https://user-images.githubusercontent.com/1581429/68566590-12112200-0457-11ea-9c7e-3cac669cd5cc.png)

**Comment by andrerpena** [comment]
Please reopen if needed
