### ISSUE TITLE
Use defaultValue as value on Textarea

### ISSUE THREAD

**Issue by emersonlaurentino** [andrerpena/react-mde#195]
Using `value` in textarea, I automatically need to use `onChange` tied to `setState` to add the new value. In my context, the initial value to be rendered to no textarea is provided by the server, while the user is editing the text, there is a debounce that gets the modifications sent to the server, I don't need to save those modifications locally, so I don't need to use the `setState`. Using `defaultValue` in textarea, I do not need to use` setState` next to `onChange` since this is a problem because I am using debounce.

**Comment by andrerpena** [comment]
@emersonlaurentino I'm sorry but could you clarify what exactly do you want?

**Comment by emersonlaurentino** [comment]
Yes, this is my code. The initial value of the editor is a data that is saved in my database, when I modify this data by the editor, I send the new data back to the database and I don't need to use the setState attached to my `handleChange`. However, when a textarea uses the `value` attribute it automatically requires it to use the `onChange` attribute to be responsible for updating the textarea value. What I am asking is to replace the textarea `value` attribute with `defaultValue` because it maintains the current behavior and allows others to use onChange without setting the value locally.

```jsx
export const Editor = () => {
  const { id } = useParams();
  const { data } = useQuery(QUERY, { variables: { id } });
  const [update, { loading }] = useMutation(UPDATE);
  const [selectedTab, setSelectedTab] = useState();
  const handleChange = debounceEvent((story: string) => {
    update({ variables: { id, input: { story } } });
  }, 400);
  return (
    <ReactMde
      value={data.story}
      onChange={handleChange}
      commands={COMMANDS}
      selectedTab={selectedTab}
      onTabChange={setSelectedTab}
      generateMarkdownPreview={(markdown: any) =>
        Promise.resolve(converter.makeHtml(markdown))
      }
    />
  );
};

```
