### ISSUE TITLE
Feature: handle preview outside ReactMde; how to remove Write/Preview 

### ISSUE THREAD

**Issue by jacargentina** [andrerpena/react-mde#197]
I want to handle my preview completely; i need to remove the write/preview tabs. If a PR can be accepted for this i'm open to contributing.

**Comment by jacargentina** [comment]
@andrerpena can you take a look? Made the PR for this.

**Comment by shahidify** [comment]
@jacargentina would you mind sharing how you're planning to handle preview separately (outside ReactMde)?

**Comment by andrerpena** [comment]
@jacargentina Thank you so much for your contribution. It is now published on 7.7.0

**Comment by andrerpena** [comment]
Fixed by: https://github.com/andrerpena/react-mde/pull/198

**Comment by haszari** [comment]
Awesome - I was looking for this feature too! Would be great to have this documented e.g. in the readme too :)
