### ISSUE TITLE
Configuring Showdown + React MDE for syntax highlighting

### ISSUE THREAD

**Issue by veeral-patel** [andrerpena/react-mde#199]
Thank you for this project @andrerpena!

I'd like to write code blocks with syntax highlighting, like GitHub has, in React MDE:

```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```

I know this is the responsibility of Showdown, not React MDE, but you have an example of how to configure Showdown with React MDE to enable syntax highlighting?

[The demo](https://andrerpena.me/react-mde/), I noticed, doesn't support syntax highlighting.

**Comment by andrerpena** [comment]
All I know is that Showdown allows you to set up a converter with options.

Example:

```
const converter = new Showdown.Converter({
  tables: true,
  simplifiedAutoLink: true,
  strikethrough: true,
  tasklists: true
});
```

This converter, apparently, supports extensions. There is an extension for syntax highlighting but I have never tested it: https://www.npmjs.com/package/showdown-highlight

The converter object can be passed to react-mde. Check the demo: https://codesandbox.io/s/react-mde-latest-9i70s.

If this does not solve your problem, please let me know.

**Comment by andrerpena** [comment]
Please let me know if you need more help
