### ISSUE TITLE
Removing event listeners

### ISSUE THREAD

**Issue by pwolaq** [andrerpena/react-mde#2]
`bind` every time creates a new function, so removing event listeners like that won't work:
```javascript
    componentDidMount() {
        document.addEventListener('click', this.handleGlobalClick.bind(this), false);
    }

    componentWillUnmount() {
        document.removeEventListener('click', this.handleGlobalClick.bind(this), false);
    }
```

**Comment by andrerpena** [comment]
Thanks, I'll look into this

**Comment by andrerpena** [comment]
@pwolaq can you check if this is the recommended way of solving this problem? https://github.com/andrerpena/react-mde/blob/master/src/components/HeaderItemDropdown.js

Please feel free to reopen this, otherwise. Thank you.

**Comment by pwolaq** [comment]
I have seen somewhere in the documentation that binding should be done in constructor, checking in `componentWillUnmount` is unnecessary then

I will create PR with few more changes in a moment
