### ISSUE TITLE
Mentions support

### ISSUE THREAD

**Issue by veeral-patel** [andrerpena/react-mde#200]
Hi @andrerpena! I noticed you opened an issue two years ago about adding mentions support:

https://github.com/andrerpena/react-mde/issues/14

However, looking at the README, I'm not sure how to setup mentions with React MDE. I'd like the mentions to look the way they do on GitHub.

Any pointers?

**Comment by andrerpena** [comment]
Now that I am back working on react-mde, I will prioritize it. I, myself, need support for this for a project I have that uses react-mde. I'm starting to work on this right now. To be honest, I'm not sure how you would implement it before I add built-in support. =/. As for the ETA, I will update this issue as soon as I know. Thanks for the suggestion.

**Comment by veeral-patel** [comment]
@andrerpena These articles might help you

https://blog.campvanilla.com/reactjs-input-trigger-github-twitter-mentions-8ad1d878110d

https://github.com/abinavseelan/react-input-trigger

https://github.com/signavio/react-mentions

**Comment by andrerpena** [comment]
@veeral-patel Thank you very much. I'm following the medium article you suggested. Expect this feature to be released soon =)

**Comment by veeral-patel** [comment]
@andrerpena No problem, how can I find out once it's ready to be used?

**Comment by andrerpena** [comment]
So I don't know when it is going to be ready but probably 2 weeks.
I will send you a message here when I close this issue =)

**Comment by veeral-patel** [comment]
@andrerpena Thank you very much!

**Comment by andrerpena** [comment]
Done. Enjoy!

**Comment by veeral-patel** [comment]
Thank you @andrerpena! Is there an easy way to get all the mentioned usernames from a React MDE textarea?

While I could write a regex which does this, I'm wondering if there's an easier solution.

**Comment by andrerpena** [comment]
Hi @veeral-patel I don't think there is an easier solution. If you don't write the Regex, I will have to right something similar and I don't think it will be generic enough to meet all users need. In this case, you better handle it on the application layer.

**Comment by veeral-patel** [comment]
@andrerpena Got it, no worries!
