### ISSUE TITLE
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by jasonlor** [andrerpena/react-mde#201]
Using typescript with
    "react-markdown": "^4.2.2",
    "react-mde": "^7.6.2",

I'm seeing this error. It looks like it's been encountered previously.

> React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

My React Markdown code below is as follows:
```
import ReactMarkdown from "react-markdown"
import ReactMde from "react-mde"
import "../node_modules/react-mde/lib/styles/scss/react-mde-all.scss"

  <ReactMde
        value={value}
        onChange={setValue}
        selectedTab={selectedTab}
        onTabChange={setSelectedTab}
        generateMarkdownPreview={(markdown: string) => Promise.resolve(<ReactMarkdown source={markdown} />)}
      />
```

If i remove ReactMde from my component, the error goes away.
I've attempted to remove ReactMarkdown and the error seems to be with ReactMde.

**Comment by jasonlor** [comment]
Further debug, it looks like server side rendering of the component is fine. 
Client side rendering returns this error, the object isn't being recognized as a React.component.

I'm using the following versions of react and react-dom.

```
    "react": "^16.12.0",
    "react-dom": "^16.12.0",

```

**Comment by andrerpena** [comment]
Thanks for letting us know @jasonlor
