### ISSUE TITLE
Auto-save

### ISSUE THREAD

**Issue by veeral-patel** [andrerpena/react-mde#204]
Hi! I'd like to implement auto-save, like Google Docs. Any resources I can check out to implement this? Is this something that's doable with React MDE?

**Comment by andrerpena** [comment]
React-mde is a controlled component. You receive an event when the text change and have to re-render it. You can also just alto save anything.

What do you think is missing in react-mde itself to help with that? I can only think of a visual indication of whether it has been saved or not, within the component itself, but we would have to think if it actually makes sense, and the best way to implement that

**Comment by andrerpena** [comment]
Please feel free to reopen it if you need further help
