### ISSUE TITLE
react-mde with formik not updating Content

### ISSUE THREAD

**Issue by vamsi981** [andrerpena/react-mde#205]
Hi,

we tried including react-mde with formik "onchange" event not updating the content. Below is sample comde of formik with editor

`<Formik
                                validationSchema={pageCreationSchema}
                                onSubmit={this.handleSubmit}
                                initialValues={itemData}
                                enableReinitialize
                            >
                                {({
                                    handleSubmit,
                                    handleChange,
                                    handleBlur,
                                    values,
                                    touched,
                                    isValid,
                                    errors,
                                }) => (
                                        <Form noValidate className="container-fluid" onSubmit={handleSubmit}>

 <Form.Row>
                                                <Form.Group as={Col} md="12" >
                                                <ReactMde
        value={values.htmlContent}
        onChange={handleChange}
        selectedTab={selectedTab}
        textAreaProps={{
            name:'htmlContent'
        }}
        onTabChange={this.setSelectedTab}
        generateMarkdownPreview={markdown =>
          Promise.resolve(converter.makeHtml(markdown))
        }
      />
                                                </Form.Group>
                                            </Form.Row>
</Formik>`

**Comment by andrerpena** [comment]
Can you please clarify what is not working?

**Comment by ericchernuka** [comment]
I believe if you’re using `handleChange` you need to provide it the field name it’s changing. So you’ll need to use `handleChange(‘markdown')`. This should work since the onChange handler from react-mde returns only the value instead of an event.

**Comment by andrerpena** [comment]
@vamsi981 does that solve your problem?

**Comment by andrerpena** [comment]
Please feel free to reopen if needed

**Comment by AleksaC** [comment]
Using `handleChange` didn't work for me. Instead I used [`setFieldValue`](https://formik.org/docs/api/formik#setfieldvalue-field-string-value-any-shouldvalidate-boolean--void). It would go like this for the example above:
```javascript
onChange={(content) => {
  setFieldValue("htmlContent", content);
}}
```
