### ISSUE TITLE
How to use full screen/page for better documentation authoring

### ISSUE THREAD

**Issue by jacargentina** [andrerpena/react-mde#208]
I cant find any way to:
- Disable height "grip"
- Make editor full page height

This way the editing is more "document editor" like. Maybe i'm missing something?

**Comment by andrerpena** [comment]
I didn't implement a way to disable the height grip, but that is a good idea.. I will do it. After that, making the editor full height will be a matter of adding custom CSS classes, which is already possible.

I will update this issue when it is completed.

**Comment by jacargentina** [comment]
@andrerpena can i help with this?

**Comment by jacargentina** [comment]
@andrerpena PR available for this. Cheers!
