### ISSUE TITLE
Add release tags for > 7.8.0

### ISSUE THREAD

**Issue by fgblomqvist** [andrerpena/react-mde#211]
This is a great and much-needed project, love the plug'n'play-style implementation. Looking forward to the design updates over time too!

Noticed that there are no releases on GitHub for versions newer than 7.8.0. Would be helpful if you would add those (along with some simple changelogs)! The main reason is to make it easier to understand what has changed with each update (so while these tags won't help me, future tags will).

**Comment by andrerpena** [comment]
Thanks for the kind words. I will make an effort to keep release tags updated. I added release info for 8.0.0 and 8.0.2. https://github.com/andrerpena/react-mde/releases
