### ISSUE TITLE
Suggestions showing up in the wrong place

### ISSUE THREAD

**Issue by ivanbanov** [andrerpena/react-mde#224]
The suggestions dropdown only takes the correct place if the container didnt scroll yet.
It's probably happening because the dropdown position is not considering the container scroll position

![bug](https://user-images.githubusercontent.com/2953018/77303565-77253000-6cf3-11ea-8e8b-5bd46908c05f.gif)

**Comment by andrerpena** [comment]
@ivanbanov Thanks a lot for your contribution
