### ISSUE TITLE
Custom textAreaRef breaks suggestions

### ISSUE THREAD

**Issue by ivanbanov** [andrerpena/react-mde#228]
Using a custom textAreaRef breaks the TextArea handlers used to control suggestions.
I'd say that ideally, the TextArea should look for the ref in the TextArea props as well.
Could probably be done here https://github.com/andrerpena/react-mde/blob/master/src/components/TextArea.tsx#L75-L81

**Comment by andrerpena** [comment]
Hey @ivanbanov . Thanks for reporting. I will look into this soon

**Comment by andrerpena** [comment]
@ivanbanov 

> Using a custom textAreaRef breaks the TextArea handlers used to control suggestions
What do you mean by "custom textAreaRef".. Can you clarify a bit more what the problem is?
