### ISSUE TITLE
Add hotkeys for text formatting in the editor

### ISSUE THREAD

**Issue by antonioduarte** [andrerpena/react-mde#233]
This is allowed by the GitHub editor and its pretty handy.

Some examples are: 

<kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>P</kbd>  - Toggle `Write/Preview` 

<kbd>CTRL</kbd> + <kbd>b</kbd> - Add **bold** text  

<kbd>CTRL</kbd> + <kbd>i</kbd> - Add *italic* text 

Are you planning to support them? Thanks!

**Comment by andrerpena** [comment]
I like the idea.. :)

**Comment by antonioduarte** [comment]
@andrerpena I saw you added some hotkeys on v10. Thank you!
