### ISSUE TITLE
componentWillReceiveProps has been renamed message

### ISSUE THREAD

**Issue by dannorcott** [andrerpena/react-mde#242]
Hi - is everyone else getting "Warning: componentWillReceiveProps has been renamed, and is not recommended for use" when switching over to preview tab?

<img width="1419" alt="Screenshot 2020-05-01 at 08 49 31" src="https://user-images.githubusercontent.com/52197623/80791206-c7ac6a80-8b88-11ea-93f0-f40b341dcfcf.png">

**Comment by andrerpena** [comment]
Yes this is annoying. This PR https://github.com/andrerpena/react-mde/pull/231 should fix it but I am focusing in releasing 10.0.0 with save image support.. I will go back and fix it soon

**Comment by dannorcott** [comment]
Thank you, that's great to hear. Component much appreciated :)

**Comment by dannorcott** [comment]
Hah pressed the wrong button :)
