### ISSUE TITLE
use onBlur?

### ISSUE THREAD

**Issue by roeljohn** [andrerpena/react-mde#247]

**Comment by DaskJeeves** [comment]
I am also having this issue of the editor not triggering the onBlur function when clicking away. Anyway successfully solved this?

**Comment by roeljohn** [comment]
@DaskJeeves since we don't have onBlur. I just put pass data in state after I click submit in button. But I realize onChange not really my issue why my form slow lol it turns out the issue is the way I put the instances in each form in ant design component lol.

**Comment by andrerpena** [comment]
I made this sandbox as an example of how onBlur should work and apparently it is working.. 
https://codesandbox.io/s/react-typescript-n6z1u?file=/src/index.tsx

**Comment by ivanbanov** [comment]
@andrerpena it can still be "broken", see #263
