### ISSUE TITLE
CSS not rendering properly on first load

### ISSUE THREAD

**Issue by dannorcott** [andrerpena/react-mde#249]
Hi, thanks for the component - I have a small problem. On first load, often the CSS isn't rendered:

<img width="342" alt="Screenshot 2020-06-17 at 09 21 17" src="https://user-images.githubusercontent.com/52197623/84874065-f9678b00-b07b-11ea-87f4-fcfe30cca90e.png">

A refresh clears it up, and there's nothing in the console. I'm importing the CSS with:

```
import 'react-mde/lib/styles/css/react-mde-all.css';
```

Is there any obvious thing that might be causing this?

Thanks!
Dan

**Comment by andrerpena** [comment]
Thanks for reporting. I dont think this is being caused by React-mde itself. My bet is that there is something weird with the way CSS importing is implemented on your project

**Comment by dannorcott** [comment]
Thanks for the response - if I get to the bottom of it I'll post the fix here, in case the same thing happens to anyone else.
