### ISSUE TITLE
Substitute for command children[]?

### ISSUE THREAD

**Issue by bravnaa** [andrerpena/react-mde#253]
As of may 2. a commit to remove the children array property from commands, allowing for a drop-down menu, was pushed. As of now i am unable to see a way to implement such a dropdown menu to execute subcommands of my own. Why was this feature removed, and does there currently exist a substitute for it?

**Comment by fortytw2** [comment]
Just encountered the same issue going through and updating all of our deps. Seems like the demo headerCommand was also significantly reduced in functionality.

Would a patch to restore this feature be welcome?

**Comment by bravnaa** [comment]
In my use case i got away with settling for version 9.1, as this version still includes the children[] array. However this is not a long-term sound solution and i would appreciate if this is taken into consideration in future updates.

**Comment by jacargentina** [comment]
Hey! I've created a for with some extra features, and this is also included I think; maybe you can try and post any issues or things needed.
https://jacargentina.github.io/react-mde/
