### ISSUE TITLE
Adding link is not working in the following scenario

### ISSUE THREAD

**Issue by qburst-dhinsha** [andrerpena/react-mde#255]
Suppose we have added a URL directly to the `Write` part. After that, by selecting the URL, we have clicked the `add a link` button, then `Write` part will be as follows,
`[](https://www.npmjs.com/package/react-mde)`

hence its does not show the actual page on clicking the link from `Preview` part

**Comment by andrerpena** [comment]
I am not really sure what the problem is. I just checked the generated link for `[react-mde](https://www.npmjs.com/package/react-mde)` and it does work.

**Comment by qburst-dhinsha** [comment]
@andrerpena thanks for your response.
I'm currently using version 8.3.0.
If I follow the above steps in version 8.3.0, `write` section will be as follows,
[https://www.npmjs.com/package/react-mde](url)

Following demo producing the same issue
https://andrerpena.me/react-mde/
Add a URL directly to the `Write` part. After that, by selecting the URL, click the `add a link` button, then `Write` part will be as follows,
`[https://andrerpena.me/react-mde/](url)`

But I can't get the issue in this commenting section, which is working as expected.
