### ISSUE TITLE
Arabic Terms

### ISSUE THREAD

**Issue by leanaAlq** [andrerpena/react-mde#256]
Thank you for this light, well written library. I saw that the library is written with consideration of i18n. It would be great to add Arabic terms and have language props available.

**Comment by andrerpena** [comment]
Would you be able to tell me how this file should look like in Arabic? https://github.com/andrerpena/react-mde/blob/master/src/l18n/react-mde.en.ts

**Comment by leanaAlq** [comment]
sure thing!
write: "تحرير",
preview: "معاينة",
uploadingImage: "جاري رفع الصور..."

**Comment by andrerpena** [comment]
Thank you! I will add it
