### ISSUE TITLE
Command.buttonComponentClass doesn't work

### ISSUE THREAD

**Issue by abulyshkin** [andrerpena/react-mde#260]
looks like this property doesn't work and has no effect on a rendered button in toolbar.
either I'm missing something either it is not passed to ToolbarButton component and always undefined in `const finalButtonComponent = buttonComponentClass || "button";`

"react-mde": "10.1.0"

**Comment by abulyshkin** [comment]
If you add line `buttonComponentClass={c.buttonComponentClass}` to Toolbar.tsx at line 89 and `buttonComponentClass: command.buttonComponentClass` to ReactMde.tsx at line 211 that should fix the issue

**Comment by andrerpena** [comment]
On this commit https://github.com/andrerpena/react-mde/commit/3c24e15aad43cc9da1aa0245764cc156a1a6c9f2 I made the changes you suggested. Sorry for that. It should be there on version 10.2.1

**Comment by andrerpena** [comment]
but to be very honest I didn't test this myself.. just passed down the prop which apparently didn't cause any problem
