### ISSUE TITLE
Can we have preview side by side instead of tab ?

### ISSUE THREAD

**Issue by ad1992** [andrerpena/react-mde#262]
Thank you @andrerpena for the awesome library. 
It would be great if preview can be seen side by side instead of switching tabs.

**Comment by andrerpena** [comment]
Thanks. I am really sorry but I have to reject this proposal. Some people want the preview on the side. Some people below like on Stackoverflow. Some poeple as a tab, like Github.

The only way I can possibly maintain this library, which is already really hard, is by limiting the scope. I decided to limit the scope to Github's MD editor.
