### ISSUE TITLE
Issues with Snowpack (maybe esm?)

### ISSUE THREAD

**Issue by ken210** [andrerpena/react-mde#269]
I tried to port one small app from webpack to snowpack and found an issue with react-mde.

### Steps to reproduce:

Create a [react/typescript snowpack](https://github.com/pikapkg/snowpack/tree/master/packages/@snowpack/app-template-react-typescript) app 
`npx create-snowpack-app app --template @snowpack/app-template-react-typescript`

Follow the example in [readme file](https://github.com/andrerpena/react-mde/blob/master/readme.md)

### Error (s)

**Showdown is not a constructor.**
This is most likely not an issue with react-mde and can be fixed by changing the import line to:
`import Showdown from 'showdown';`

**react-mde.js:1581 Uncaught TypeError: Cannot read property 'getDefaultCommandMap' of undefined**
this error happens here:
```JavaScript
this.commandMap = __assign(__assign({}, js.__moduleExports.getDefaultCommandMap()), (customCommands || {}));
```
Apparently this happens because of this import usage:
https://github.com/andrerpena/react-mde/blob/master/src/commands/command-orchestrator.ts#L9
`import something from "..";`

So the fix for that error is straightforward: (https://github.com/ken210/react-mde/commit/392290ddc4883598f963689576a92ada77595581)

But still I'm not 100% happy with this solution yet since it requires some ugly stuff in user-land code:

```TypeScript
import mde from 'react-mde'; // for some reason I can't get the default export
import Showdown from 'showdown'; // this import changed

// @ts-ignore
const ReactMde: typeof mde = mde.default; // this is not cool
const converter = new Showdown.Converter();
```

**Comment by ken210** [comment]
Maybe related to https://github.com/andrerpena/react-mde/issues/250

**Comment by andrerpena** [comment]
Hey @ken210.
As I understand you have 2 problems:
1. I should stop importing from `..`. Ok I can do that.
1. The default export is not working and you don't know why.

Is it OK if I just resolve (1) based on your fork?

**Comment by ken210** [comment]
HI @andrerpena I Believe so yes.

It's is not a definitive fix for ESM as it seems, but as least people can import the lib.

Sounds like an improvement 😅
