### ISSUE TITLE
image paste,md format

### ISSUE THREAD

**Issue by deligent-ant** [andrerpena/react-mde#275]
now,react-mde:
```
![image](https://picsum.photos/300)皇冠.png
```
but we hope

```
![皇冠.png](https://picsum.photos/300)
```

**Comment by andrerpena** [comment]
React-mde displays`![image](https://picsum.photos/300)` because this is what the Github editor does. Can you elaborate a bit on what the problem is?

**Comment by deligent-ant** [comment]
ok,when we upload a file,the file name is `good.jpg` and the url is `https://picsum.photos/300`.and we hope the  md is 

![good.jpg](https://picsum.photos/300),  but we get ![image](https://picsum.photos/300)good.jpg . and we have to delete word good.jpg in editor.

at the same time,can we format the md customized with the file url

**Comment by andrerpena** [comment]
I am sorry that I don't understand what you mean.. you sad the text `good.jpg` was added afterwards, like this?

```
 ![image](https://picsum.photos/300)good.jpg
```

I am trying to reproduce this without success
