### ISSUE TITLE
[Quetion] Disable button

### ISSUE THREAD

**Issue by nagayev** [andrerpena/react-mde#288]
Hello. Thank you for nice library.
Can I disable button with code logo?
I want to use this lib on my website and users aren't coders.

**Comment by nico-w** [comment]
You can define your own toolbar commands by using the `toolbarCommands` prop.
This example will only allow, bold and italic text plus links and images:
```
// ...
import ReactMde from 'react-mde';

<ReactMde
      // ...
      toolbarCommands={[
          [
              'bold',
              'italic',
              'link',
              'image',
      ]}
      // ...
  />
```

Explanation in docs:

> toolbarCommands?: string[][]: Array of array of strings, indicating which commands should be displayed. Each outer array is a group. Example: [["code", "bold"], ["italic"]]. The default list can be obtained with import { getDefaultToolbarCommands } from 'react-mde', getDefaultToolbarCommands()

See more here: https://github.com/andrerpena/react-mde#react-mde-props

Hope this helps 😊

**Comment by nagayev** [comment]
@nico-w Thanks
