### ISSUE TITLE
Is it possible to execute a command externally?

### ISSUE THREAD

**Issue by polcats** [andrerpena/react-mde#292]
Something like executing a command from a function and not from the toolbar buttons?

**Comment by Stas-Buzunko** [comment]
yes, you need to use ref
const someref = useRef(null)

<ReactMde
              ref={c => {someref.current = c}}
 /> 
 
 
 then you can trigger different commands using someref.current.handleCommand(someCommand) or using other methods

**Comment by polcats** [comment]
> yes, you need to use ref
> 
> ```
> const someref = useRef(null)
> 
> <ReactMde
>   ref={c => {someref.current = c}}
> /> 
>  
> ```
> 
> then you can trigger different commands using `someref.current.handleCommand(someCommand)` or using other methods

Thank you!
