### ISSUE TITLE
SuggestionsDropdown is not compatible with Class components

### ISSUE THREAD

**Issue by mmomtchev** [andrerpena/react-mde#297]
`SuggestionsDropdown` uses `useCallback` which makes it incompatible with Class components

What is the added benefit of `useCallback`? Is it really necessary - both callbacks `handleSuggestionClick` and `handleMouseDown` are deep inside the map? One doesn't gain almost anything in terms of performance?

**Comment by andrerpena** [comment]
Thanks for submitting the PR. This has been published on 11.0.5
