### ISSUE TITLE
Preview not working with react-markdown latest version (6.0.1)

### ISSUE THREAD

**Issue by rafaelguedes** [andrerpena/react-mde#320]
First of all: thanks for this cool editor.

Using `react-markdown` @ 6.0.1 is causing the preview not to work.

Is there any chance that you can fix this?

**Comment by paescuj** [comment]
With `react-markdown` >=6.0.0 you now need to pass the markdown variable as children:
```
generateMarkdownPreview={(markdown) =>
  Promise.resolve(
    <ReactMarkdown>{markdown}</ReactMarkdown>
  )
}
```
