### ISSUE TITLE
Can code highlighting be supported

### ISSUE THREAD

**Issue by GavinKings** [andrerpena/react-mde#44]
Can code highlighting be supported？

**Comment by andrerpena** [comment]
I'm definitely not planning to support it natively. However, I'll leave this issue open and take a look at how people are implementing code highlight in Showdown.

Here are some threads about it:

https://github.com/showdownjs/showdown/issues/215
https://github.com/showdownjs/showdown/issues/325

I'll then try to find the best way to let users to hook into the Showdown rendering process from `react-mde`.

**Comment by andrerpena** [comment]
If I find a way to let users hook into the Markdown rendering process so you can use `highlight.js`, for instance, I'll add an example to the documentation.

**Comment by andrerpena** [comment]
I tried to release 2.* in a compatible way but I still didn't test if your code still works, even though I presume it does, except for the `textareaId` and `textareaName` props that are now `textareaProps`.
