### ISSUE TITLE
Error: Warning: Unknown DOM property contenteditable. Did you mean contentEditable?

### ISSUE THREAD

**Issue by michaelryancaputo** [andrerpena/react-mde#49]
Getting the console error `Warning: Unknown DOM property contenteditable. Did you mean contentEditable?`

I took a look at the source code and found this on a textarea element. Not sure it's necssary since textarea is editable by default.

Happy to submit a PR fixing this.

**Comment by andrerpena** [comment]
Hey @michaelryancaputo , thanks for spotting it. It's a leftover code from my attempt to make `document.insertText()` to work on Firefox. It's useless. I can fix it but a MR would be welcome too :)

**Comment by michaelryancaputo** [comment]
#50

**Comment by andrerpena** [comment]
Thank you. Merged. I'll push to NPM later today.
