### ISSUE TITLE
Is there a new normal react JSX version of this; not typescript?

### ISSUE THREAD

**Issue by daanishnasir** [andrerpena/react-mde#54]
Trying to get this working on a big project i'm working on where I don't have any ts files.

**Comment by andrerpena** [comment]
Hi.. I compile the `ts` and `tsx` files to regular javascript. Here's a demo: https://github.com/andrerpena/react-mde-js-demo. Feel free to re-open this project if you have any problems.

**Comment by LennyLip** [comment]
`Uncaught (in promise) TypeError: classnames_1.default is not a function`
at
`        return (React.createElement("div", { className: classnames_1.default("react-mde", "react-mde-tabbed-layout", className) },
`

**Comment by andrerpena** [comment]
Thanks for reporting. When you say the demo link is broken. What demo you mean exactly?

**Comment by LennyLip** [comment]
The link from your comment https://github.com/andrerpena/react-mde/issues/54#issuecomment-345441127

**Comment by andrerpena** [comment]
@LennyLip oh yes you are right. I'll fix it! Thanks for letting me know

**Comment by andrerpena** [comment]
The demos were fixed:


- [Demo](http://andrerpena.me/react-mde/). 
- [Demo on CodeSandbox](https://codesandbox.io/s/vm1k17ymq0).
- [Demo *source* in TypeScript](https://github.com/andrerpena/react-mde/tree/master/demo).
- [Demo *source* in JSX](https://github.com/andrerpena/react-mde-test).
