### ISSUE TITLE
React markdown feature added to qualitative indicator updates

### ISSUE THREAD

**Issue by AkvoAnt** [andrerpena/react-mde#55]
To allow Users to format their indicator reporting updates we introduce the React markdown feature.

https://github.com/andrerpena/react-mde

![react markdown](https://user-images.githubusercontent.com/26227538/32951407-c49200e0-cb77-11e7-9cda-bf3294db7acb.png)

**Comment by andrerpena** [comment]
I'm sorry but.. What is this issue about?

**Comment by andrerpena** [comment]
I'm closing because I can't understand what is the request

**Comment by AkvoAnt** [comment]
Hi Andre, 

Apologies. I was using the link for your Markdown example and didn't realise it tagged you.

- Anthony
