### ISSUE TITLE
Support table?

### ISSUE THREAD

**Issue by vision-ken** [andrerpena/react-mde#59]
Does react-mde support table?
I tried the following in the live demo, but no effect:
```
| 22   | 44   |
| ---- | ---- |
| 222  | 33   |
```

**Comment by andrerpena** [comment]
You are right. Bug. Thanks for reporting

**Comment by andrerpena** [comment]
That's because [Showdown](https://github.com/showdownjs/showdown) doesn't handle tables by default, unless you pass it as an option. This is probably for performance reasons.

Tonight I'll release version `2.1.0` and I'll add an option to pass options to Showdown.

**Comment by andrerpena** [comment]
Fixed on 2.1.1. Now you can pass `showdownOptions={{tables: true}}` and get tables working

**Comment by RobinJayaswal** [comment]
Thoughts on adding a button on the editor for inserting a table?
