### ISSUE TITLE
Feature for adding markdown list item on Enter key press and a Tab feature in textbox area

### ISSUE THREAD

**Issue by daanishnasir** [andrerpena/react-mde#61]
Right now if you type markdown as followed : 

- asdlkfjasdlfk    (and then press enter)
-         <--- it would be awesome if it automatically added a  "-"   or 1. , 2. , etc automatically depending on if its a bullet or numbered list. 

Similar to how Microsoft word does it when pressing enter on Lists. 

Also, a feature that when you are done writing the list items, a way to cancel out the last markdown "-" or 1.  by clicking enter and or backspace; just like how Microsoft Words does it as well.  Example:

- This is
- a test showing
- example 
-   // at this point pressing enter or backspace should remove the markdown "-"

Lastly, a feature that when you key press Tab, it will actually tab over in the textbox (or 4 spaces) and reflect as so in the HTML as a Tab instead of selecting another element on the page.

**Comment by andrerpena** [comment]
A appreciate your interest and it's indeed a cool feature, but since GitHub and Stackoverflow don't support this, I'm also not kin of supporting it.

I'd rather, in the future, provide an example of how to leverage the existing text helpers to help you to implement this on your own.

Sorry.
