### ISSUE TITLE
Scrolling jumps to the end when using the toolbar comands

### ISSUE THREAD

**Issue by emirotin** [andrerpena/react-mde#62]
Repro:
* go to http://andrerpena.me/react-mde/
* type lots of text to have the scrolling in the textarea
* scroll to the beginning
* select a word
* hit "B" or "I" icon
* the selected text is properly wrapped, but the cursor jumps to the end of the textarea

**Comment by andrerpena** [comment]
Thanks for reporting. Indeed a bug. Added to Roadmap.

**Comment by andrerpena** [comment]
Just for reference: https://github.com/facebook/react/issues/955

**Comment by andrerpena** [comment]
Enjoy!
