### ISSUE TITLE
UL/OL commands set wrong selection, affects UX

### ISSUE THREAD

**Issue by emirotin** [andrerpena/react-mde#63]
Repro:
* go to http://andrerpena.me/react-mde/
* click any of the two list command buttons
* the list bullet is properly inserted but it and the following space are selected

Why is it bad? Becuase the users expect that after clicking on the list icon they can start typing the list item content. But because of the selection they overwrite the bullet.

**Comment by andrerpena** [comment]
Thanks for reporting. Indeed a bug. Added to Roadmap.

**Comment by andrerpena** [comment]
I'm going to follow the GitHub behavior:

- If the selection is in 1 line, including the case where the selection start and stop is in the same position, 
 or if there's no selection at all (no focus) the resulting selection will be AFTER the list prefix (e.g `- `or ` 1. `).
- If the selection is multi-line, the selection will encompass the list prefixes.

**Comment by andrerpena** [comment]
Enjoy!

**Comment by emirotin** [comment]
Thanks!
