### ISSUE TITLE
Can you document adding commands better in JS?

### ISSUE THREAD

**Issue by d0lb33** [andrerpena/react-mde#67]
Currently I have no idea on how to add commands to ReactMDE in its current state without modifying the node modules.

**Comment by d0lb33** [comment]
Wow. Well so I apaprently didnt know you had to double wrap the commands until I took a look at how the getDefaultCommands was returning. I am an idiot. All fixed now!

**Comment by andrerpena** [comment]
I'm sorry for the confusion @d0lb33 . I've just updated the docs to prevent future users to have the trouble you had.

If you need anything, I'm here. =)

Glad you're using `React-mde`

**Comment by d0lb33** [comment]
@andrerpena Thanks!
