### ISSUE TITLE
Stuck highlighting within textarea box

### ISSUE THREAD

**Issue by daanishnasir** [andrerpena/react-mde#68]
Weird issue going on, though it doesn't seem to be occurring in your demo but i figured maybe someone here would know how to go about fixing it...

Every time i highlight anything in the textarea box, I can't seem to un-highlight the selection after clicking within the textarea box again. 

It does however get unhighlighted (text gets un-selected) once I click outside of the textarea box. 

Any idea why?

**Comment by andrerpena** [comment]
Too bad you're having this problem. I just tried to reproduce in the demos and I just couldn't.
I'll try harder another time and I'll leave this issue open in case anyone else knows what might be going on.
Cheers.

**Comment by daanishnasir** [comment]
Found the issue, basically i had another function tied to textarea props that had a preventDefault();

**Comment by andrerpena** [comment]
I'm glad to know! Thanks for letting me know.
