### ISSUE TITLE
Clicking a command not selecting the highlighted portion. 

### ISSUE THREAD

**Issue by daanishnasir** [andrerpena/react-mde#70]
I'm using react-mde through the 3 sub component approach. Once i click bold (or any command) for example, it selects the entire string instead of the portion that i have highlighted 

Example:

Text value: This is the test.

I've highlighted the word 'the' and clicked bold command. 

Which results in this 

           **This is the test**

Where it really should result to

          This is **the** test.

(which showdown then bolds the entire string because of the markdown syntax)

On a side note, it works fine when react-mde is used as a single wrapper component instead of with sub-components.

Not sure if its a bug, or something on my end. Can you post an example of react-mde in JS that uses all 3 sub components with handleCommand()..  Maybe i'm missing something in setting up the handleCommand.  Made some comments below in my component to help understand the issue. 

```         

    let realCommands = [ 
      [ReactMdeCommands.makeHeaderCommand, ReactMdeCommands.makeBoldCommand, ReactMdeCommands.makeItalicCommand], 
    [ReactMdeCommands.makeUnorderedListCommand, ReactMdeCommands.makeOrderedListCommand],
    ]




  handleCommand = (command: Command) => {

    //const {value: {text}, onChange} = this.props;

    let text = this.state.reactMdeValue.text;          //debugger showing correct text = "This is the test"

    let textArea = this.textArea;                    //debugger showing correct textArea = textarea.textarea-input

    const newValue = command.execute(text, getSelection(textArea));

             //here newValue is equal to **This is the test** which makes me think something is up with the 
              execute command as it should be   This is **the** test



    this.handleValueChange(newValue);

  }




  handleValueChange = value => {

    this.setState({
      reactMdeValue: value,
    });

 };




   <div>
              <ReactMdeToolbar
                commands={realCommands}
                onCommand={this.handleCommand}
                />

              <ReactMdeTextArea
                  onChange={this.handleValueChange}
                  value={this.state.reactMdeValue}
                  textAreaProps={textAreaProps}
                  textAreaRef={(ref) => this.textArea = ref}
                  />      

              <label className="group-input inputs-module">Preview</label>

              <ReactMdePreview 
                  markdown={this.state.reactMdeValue.text}
                  />
   </div>
```

**Comment by andrerpena** [comment]
Thansk for reporting in such a detailed way. I'll work on this in the next weekend.

**Comment by andrerpena** [comment]
@daanishnasir 

I have to appologize. I DID NOT ABANDON THIS PROJECT WHATSOEVER. The problem is that during the last 3 weeks I'm solely dedicated to moving from Brazil to Germany and I have lots of bureaucracy to solve, stuff to get sorted, people to visit.

I know react-mde still has it's inconsistencies and as soon as I settle in Berlin in the first week of February, I'll get back to it and solve. It's not just because I really like this project. It's also because I use it in other project and I need it to work 100%.

Thanks for your comprehension.

**Comment by andrerpena** [comment]
Closed because it is too old now
