### ISSUE TITLE
Docs don't match TS type definition for Command

### ISSUE THREAD

**Issue by mattbasta** [andrerpena/react-mde#75]
The docs say that the `icon` member of a command may be a JSX element. However, the type definition only allows strings:

> If this is a text, it will print a font-awesome `<i/>` element with the classes `fa fa-${icon}`. Passing bold will print `<i className="fa fa-bold"></i>`. If the passing value is a React element, it will print the react element.

https://github.com/andrerpena/react-mde/blob/master/src/types/Command.ts#L6

The `icon` member should conceivably be updated to `string | JSX.Element`

**Comment by andrerpena** [comment]
`string | JSX.Element` would probably be more correct. I used `ReactNode` but I don't know what would happen if you pass a number now. I'll update later. Your problem should be fixed now. Thanks for reporting.
