### ISSUE TITLE
Implement history so Ctrl + Z will work properly with commands

### ISSUE THREAD

**Issue by connerleverett** [andrerpena/react-mde#76]
Enter text, select the text, use the bold command and then press ctrl-z.

Expected Behaviour: The bold should undo.

Actual Behaviour: The bold is not undone and random text may be deleted.

**Comment by andrerpena** [comment]
Yes.. This problem sucks. Apparently, I'll have to write my own history manager for the text area.. AKA controlling Ctrl-Z myself if I want that to work.. I've spent like 4 hours trying to figure that out already Check https://github.com/andrerpena/react-mde/issues/15.

Now I only have to understand what the priorities are. I think I'm going to start with supporting tab previews like GitHub and then jumping to the history manager.

Thanks for reporting. If you have a better suggestion, feel free to share.

**Comment by andrerpena** [comment]
I'm currently working on this. The solution will be released on the 5.* version that will probably come up on March 18th.
