### ISSUE TITLE
Find a recommended library to deal with XSS

### ISSUE THREAD

**Issue by andrerpena** [andrerpena/react-mde#78]
As observed by @mattbasta in this thread: https://github.com/andrerpena/react-mde/issues/74, `React-mde` is vulnerable to XSS and this is not as simple as [described here](https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-(and-how-to-mitigate-it)). What we do have now is a prop called `processHtml` which is called before displaying the HTML in the preview panel, and this allows you to use your anti-XSS library of choice to mitigate it.

This thread is about finding a recommended one. Maybe I'll add it as an optional dependency, or possibly just suggest using it and updating the demo to include it.

**Comment by Errorname** [comment]
I'm using this showdown extension to deal with XSS: https://github.com/VisionistInc/showdown-xss-filter

**Comment by andrerpena** [comment]
Oh God. Thank you veru much! I'll update the documentation. By the way, I'm just about to release a version 5 in which the dependency over Showdown is going to be removed, but it will still be primarily used for client-side Markdown transformation, even though you can now server side render the preview. 

But I'll definitely include your suggestion on the documentation and I'll close this issue.

Thank you very much for that.

**Comment by andrerpena** [comment]
Updated the readme.md file to include your suggestion. Thank you very much.

**Comment by Errorname** [comment]
You are welcome !
