### ISSUE TITLE
Implement the GitHub layout

### ISSUE THREAD

**Issue by andrerpena** [andrerpena/react-mde#83]
After the multi-layout support was implemented https://github.com/andrerpena/react-mde/issues/73, now it's time to implement the GitHub layout, with the preview being on the side, in tabs.

**Comment by markspolakovs** [comment]
@andrerpena, if it helps, in this gist you can see how I implemented it in one of my projects: https://gist.github.com/markspolakovs/08b522e186905c270b9d9cfdf9020775

There's quite a few dirty hacks for my environment and build system, but this could be useful. (The "ghost" field is an ugly hack to get auto-resizing for the editor.)

**Comment by andrerpena** [comment]
@markspolakovs Thanks for sharing! I'll definitely take a look

**Comment by andrerpena** [comment]
[Implemented by @Nes-si](http://andrerpena.me/react-mde/?selectedKind=Layouts&selectedStory=tabbed&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) . I'll just adjust the UI and publish it as 5.5.
