### ISSUE TITLE
Focus is forcingly moved to markdown editor

### ISSUE THREAD

**Issue by ant35rookie** [andrerpena/react-mde#86]
Hello,
Thank you for this great package 

After applying this editor , I found a issue in it

** reproduction steps **
1. add react-mde
2. add other inputs
3. render
4. type something in react-mde
5. type something in other inputs
6. then focus is moved to react-mde forcingly

you can check it out with below code !
https://codesandbox.io/s/o4v4mqmrq6

```
ReactMdeDemo.js
render() {
    return (
      <div className="container">
        <ReactMde
          textAreaProps={{
            id: "ta1",
            name: "ta1"
          }}
          value={this.state.reactMdeValue}
          onChange={this.handleValueChange}
          showdownOptions={{ tables: true, simplifiedAutoLink: true }}
        />

        <input
          name="name"
          onChange={e => this.setState({ name: e.target.value })}
          value={this.state.name}
        />
      </div>
    );
  }

```

**Comment by andrerpena** [comment]
Thanks for replying, I'll investigate.. However, I'm just about to release version 5 next weekend (on the draft.js branch) and I'll try to reproduce your step on the new version and if still applies, I'll sure fix it.

**Comment by ant35rookie** [comment]
Dear andrerpena,

thank you for your support !

**Comment by ant35rookie** [comment]
Dear Andrerpena,

I found that issue is resolved with version 5 

thank you ^^

**Comment by andrerpena** [comment]
Great to hear!
