### ISSUE TITLE
onFocus

### ISSUE THREAD

**Issue by flexzuu** [andrerpena/react-mde#90]
Hey i like the new version of `react-mde` do you think we can build something in to give users control of onFocus etc? maybe even allowing to set arbitrary props of the draft-js editor.
This would allow people to use plugins with react-mde for example

**Comment by andrerpena** [comment]
Hey. I fully endorse the idea and I'd like to help.
Would you take the time to elaborate on what exactly should we do, what should I learn and what exactly would be the benefits? For example, I want to be able to support mentioning and this MIGHT help.

Thanks for contributing

**Comment by u007** [comment]
i think somehow, reactmde is stealing focus from another text input,
is there a reason for this?

i think work around is to have textareaprops to support for onfocus and onblur to handle form disabling when focus is on other field

**Comment by andrerpena** [comment]
@u007 Thanks for your report. I can't think of any reason for react-mde to be stealing focus. I'll add the possibility to pass Draft.js props in version 6

**Comment by andrerpena** [comment]
Closing because react-mde does not even use Draft.js anymore
