### ISSUE TITLE
Disable Preview 

### ISSUE THREAD

**Issue by aliogaili** [andrerpena/react-mde#91]
Hello, is there a prop to disable preview in the latest version ?

**Comment by Nes-si** [comment]
You can turn your attention to my fork, it has.

**Comment by aliogaili** [comment]
Good fork! thanks for sharing

**Comment by andrerpena** [comment]
@Nes-si thanks for your contribution. Now the `generateMarkdownPreview` is optional and `noPreview` is now on the docs to. Just published `5.2.0`. ♥️

**Comment by jyutzio** [comment]
Could you please help me in regards to disabling preview mode? I've looked around the repo and I can't seem to figure it out.

**Comment by Timer91** [comment]
@andrerpena i agree with @jyutzio, I also can't find `layout` prop with `noPreview` in the latest version.

It seems to be only available in this [file](https://github.com/andrerpena/react-mde/blob/master/docs-md/5-readme.md) ...
